version: 2
jobs:
  ruby2.6-rails5.2:
    docker:
      - image: circleci/ruby:2.6
    working_directory: ~/repo
    steps:
      - checkout
      - run: gem install bundler:2.0.2
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3
      - run: bin/test
workflows:
  version: 2
  build_and_test:
    jobs:
      - ruby2.6-rails5.2
